name: Autonomous Software Orchestrator

on:
  schedule:
    - cron: '0 7 * * *'  # Every day at 07:00 UTC
  workflow_dispatch:

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    env:
      ADO_PAT: ${{ secrets.ADO_PAT }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ADO_ORG: richardhannah
      ADO_PROJECT: CoreSupport
      ADO_REPO: CoreSupport-Manifest
      GITHUB_ORG: richardhannah
    steps:
      - name: Checkout orchestrator repo
        uses: actions/checkout@v4

      - name: Run orchestrator script
        run: bash orchestrate.sh